<?php
/** Footer: real actions, legal modal triggers, dynamic year. */
if ( ! defined( 'ABSPATH' ) ) { exit; } $c = pgm_config(); $phone_href = pgm_phone_href( $c['phone'] ); $wa_href = pgm_whatsapp_href( $c['whatsapp'] );
?></main><footer class="site-footer"><div class="container footer-grid"><div class="footer-brand"><a class="brand brand-light" href="#accueil"><img class="brand-logo" src="<?php echo esc_url( pgm_asset( 'pharmacie-logo-ivoirien.webp' ) ); ?>" alt="" aria-hidden="true"><span class="brand-copy"><strong>Pharmacie</strong><em>du Grand Marché<br>San Pédro</em></span></a><p>Un repère de santé au cœur de<br>San Pedro, Côte d’Ivoire.</p></div><div><p class="footer-label">Contact</p><a href="<?php echo esc_attr( $phone_href ); ?>">Téléphone</a><?php if ( $wa_href ) : ?><a href="<?php echo esc_url( $wa_href ); ?>" target="_blank" rel="noopener">WhatsApp</a><?php endif; ?></div><div><p class="footer-label">Navigation</p><a href="#pharmacie">La pharmacie</a><a href="#services">Services</a><a href="#conseils">Conseils</a><a href="#contact">Contact</a></div><div><p class="footer-label">Informations légales</p><button class="footer-link" data-modal-open="legal">Mentions légales</button><button class="footer-link" data-modal-open="privacy">Politique de confidentialité</button>
</div></div><div class="container footer-institutions"><p class="footer-label">Repères institutionnels</p><div class="institution-logos"><span class="institution-emblem"><img src="<?php echo esc_url( pgm_asset( 'embleme-cote-divoire-cropped.webp' ) ); ?>" alt="Emblème de la République de Côte d’Ivoire fourni par le client"></span><a href="https://www.sante.gouv.ci/accueil" target="_blank" rel="noopener" aria-label="Ministère de la Santé de Côte d’Ivoire"><img src="<?php echo esc_url( pgm_asset( 'logo-ministere-sante-ci-final.webp' ) ); ?>" alt="Ministère de la Santé, de l’Hygiène Publique et de la Couverture Maladie Universelle"></a><a href="https://ordrepharmacien.ci/" target="_blank" rel="noopener" aria-label="Ordre National des Pharmaciens de Côte d’Ivoire"><img src="<?php echo esc_url( pgm_asset( 'logo-ordre-pharmaciens-ci-cropped.webp' ) ); ?>" alt="Ordre National des Pharmaciens de Côte d’Ivoire"></a></div><small>Logos institutionnels issus de sources publiques et présentés à titre informatif.</small></div><div class="container footer-bottom"><span>© <?php echo esc_html( date_i18n( 'Y' ) ); ?> Pharmacie du Grand Marché</span><span class="footer-flag" aria-label="Côte d’Ivoire"><i></i><i></i><i></i></span><span>San Pedro · Côte d’Ivoire</span></div>
</footer>
<button class="section-back" type="button" aria-label="Revenir à la section précédente" title="Section précédente">
    <span aria-hidden="true">↑</span>
</button>
<div class="modal" data-modal="legal" role="dialog" aria-modal="true" aria-labelledby="legal-title" hidden><div class="modal-backdrop" data-modal-close></div><div class="modal-card"><button class="modal-close" data-modal-close aria-label="Fermer">×</button><p class="eyebrow">Informations</p><h2 id="legal-title">Mentions légales</h2><p>Ce site est édité pour la Pharmacie du Grand Marché, située à San Pedro, Côte d’Ivoire.</p><p>Les informations de contact, les horaires et les contenus de ce site sont à vérifier et à maintenir à jour par l’équipe de la pharmacie. Les textes de conseils santé sont généraux et ne remplacent pas un avis médical personnalisé.</p><p><strong>Responsable de publication :</strong> Dr Yacinth Ocho.</p><p><strong>Conception, direction artistique, design UI/UX, développement front-end et back-end, intégration, architecture technique et mise en production :</strong> Prince Ocho.</p><p>L’ensemble de la conception technique et visuelle du site, incluant son identité numérique, son interface utilisateur, son développement logiciel, son intégration et son déploiement, a été réalisé par Prince Ocho.</p></div></div>
<div class="modal" data-modal="privacy" role="dialog" aria-modal="true" aria-labelledby="privacy-title" hidden><div class="modal-backdrop" data-modal-close></div><div class="modal-card"><button class="modal-close" data-modal-close aria-label="Fermer">×</button><p class="eyebrow">Vos données</p><h2 id="privacy-title">Politique de confidentialité</h2><p>Ce site ne demande pas de compte et n’intègre pas de formulaire de collecte dans cette version. Les liens Appeler, WhatsApp et Google Maps ouvrent des services externes lorsque vous les activez.</p><p>Pour toute question concernant vos données ou l’utilisation du site, contactez directement la pharmacie via les coordonnées affichées.</p></div></div>
<div class="cursor-dot" aria-hidden="true"></div><div class="cursor-ring" aria-hidden="true"></div><?php wp_footer(); ?></body></html>
